import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  // ✅ Ignore auto-generated or Prisma files
  {
    ignores: [
      "src/generated/**",
      "prisma/generated/**",
      "**/*.d.ts", // optional: often generated by TypeScript
    ],
  },

  // ✅ Use Next.js + TypeScript recommended settings
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
